### ISSUE TITLE
change the background color. 

### ISSUE THREAD

**Issue by lethara97** [lethara97/Hardware_Management_System#1]
**background color in "red"**

![WhatsApp Image 2022-10-26 at 11 11 11](https://user-images.githubusercontent.com/88639083/197945160-fd1f9621-7a9f-48cc-a63c-5c727ad00c2d.jpeg)

**Comment by sano2019** [comment]
I could take this if possible :)

**Comment by KanjiZain** [comment]
Assign this issue to me will make it creative
