### ISSUE TITLE
change font style

### ISSUE THREAD

**Issue by lethara97** [lethara97/Hardware_Management_System#2]
**font style 'Times New Roman'**

![WhatsApp Image 2022-10-26 at 11 48 01](https://user-images.githubusercontent.com/88639083/197951561-a175c5d3-a6bc-4938-b7b4-ae9c84a4bdc3.jpeg)

**Comment by h-campos** [comment]
Hello, i would like to work on this could you assign to me, i just need to know what font did you want now ? (Poppins, roboto....)

**Comment by Sankalp-sa** [comment]
Hi, I have changed the font style to "Gideon roman" which is similar to times new roman you can see it the ss below 
![image](https://user-images.githubusercontent.com/102241865/197974807-12287aba-2ab8-4422-9262-76ab84559240.png)
and do you also want to change the heading font to Gideon roman ??
