### ISSUE TITLE
Add the background photo

### ISSUE THREAD

**Issue by lethara97** [lethara97/Hardware_Management_System#5]
![WhatsApp Image 2022-10-26 at 12 05 46](https://user-images.githubusercontent.com/88639083/198015154-aebc0786-0e07-48c8-86c9-b656ea0b034e.jpeg)

**Comment by sano2019** [comment]
I can take this :)

**Comment by srijoy-paul** [comment]
Hey @bandara1997 please assign me this task

**Comment by lethara97** [comment]
@sano2019 try bro

**Comment by lethara97** [comment]
@srijoy-paul you can try bro
